apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-app-deployment
  namespace: awsbedrockworkshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot-app
        image: my-chatbot-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_DATABASE
          value: "ai_database"
        - name: AWS_REGION
          value: "eu-west-1"
        - name: DB_USER # Now gets the new user from the secret
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: DB_USER
        - name: DB_PASSWORD # Now gets the new user's password
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: DB_PASSWORD
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: AWS_SECRET_ACCESS_KEY